### ISSUE TITLE
Pomysł na budynki do stawiania (co robią, statystyki itd)

### ISSUE THREAD

**Issue by exostin** [exostin/ExpiryDate#10]
- [x] Jakie mamy budynki?
- [x] Za co odpowiadają?
- [x] Jaki jest ich koszt do postawienia?
- [x] Concept arty budynków

**Comment by exostin** [comment]
Jakiś link do excela?

**Comment by Vitagunia** [comment]
[Budynki_Jednostki_Umiejetnosci_Przeciwnicy_I_WOGLE.xlsx](https://github.com/exostin/ExpiryDate/files/7966560/Budynki_Jednostki_Umiejetnosci_Przeciwnicy_I_WOGLE.xlsx)
