### ISSUE TITLE
Game design jednostek używanych do walki

### ISSUE THREAD

**Issue by exostin** [exostin/ExpiryDate#11]
https://docs.google.com/document/d/1nt-YZEfw3DywWOPYXwBiKjUG4LCSojKm/edit?usp=sharing&ouid=100603009126822552259&rtpof=true&sd=true

- [x] Dwie podstawowe jednostki
- [x] Co robią?
- [x] Jak wyglądają?
- [x] Jakie mają statystyki?

**Comment by Nexud** [comment]
[Jednostki i umiejętności.xlsx](https://github.com/exostin/ExpiryDate/files/7949847/Jednostki.i.umiejetnosci.xlsx)
