### ISSUE TITLE
Stworzyć game design document

### ISSUE THREAD

**Issue by exostin** [exostin/ExpiryDate#17]
Dokument nie powinien zajmować więcej, niż 10MB
- [ ] Adaptacja dokumentu przez @exostin do LaTeX'u/Markdown'u by zrobić ładny plik PDF

**Comment by exostin** [comment]
Jakiś plik?

**Comment by Vitagunia** [comment]
[Game Design Document.pdf](https://github.com/exostin/ExpiryDate/files/7966500/Game.Design.Document.pdf)
