### ISSUE TITLE
Pinterest moodboard

### ISSUE THREAD

**Issue by exostin** [exostin/ExpiryDate#20]
Korzystając z serwisu Pinterest (lub podobnego) stwórzcie moodboarda lub tablicę inspiracji przedstawiającą co najmniej 50 grafik z gier i innych mediów, które przedstawiają poglądowo jak może wyglądać Wasza gra. Chodzi nam o inspiracje estetyczne dla działki Experience Design

**Comment by Vitagunia** [comment]
[EXPIRY-DATE-1.pdf](https://github.com/exostin/ExpiryDate/files/7966501/EXPIRY-DATE-1.pdf)
