### ISSUE TITLE
Architektura projektu gry i game flow

### ISSUE THREAD

**Issue by exostin** [exostin/ExpiryDate#22]
Rozpiszcie architekturę projektu gry oraz game flow gracza w grze. Pliki z tymi rozpisanymi rzeczami wrzućcie na wybrany dysk w chmurze. Link do pliku podajcie poniżej (pamiętajcie o dobrych ustawieniach udostępniania!)

**Comment by Vitagunia** [comment]
https://drive.google.com/file/d/1aeaB2Q7EA5shq0BB-YpxkN-FGZ1Owywd/view?usp=sharing
