### ISSUE TITLE
Poprawić wykorzystanie maszyny stanów

### ISSUE THREAD

**Issue by exostin** [exostin/ExpiryDate#27]
obecna implementacja była robiona na szybko, żeby tylko zdążyć z milestonem i szczerze mówiąc to działa ledwo-ledwo. Możecie ją całkowicie usunąć i zaimplementować na nowo tak naprawdę

Dokumentacje wykorzystania używanej w naszym projekcie maszyny stanów możecie znaleźć tutaj: https://github.com/thefuntastic/Unity3d-Finite-State-Machine

**Comment by kubagp1** [comment]
Pomijamy ten ticket.
