### ISSUE TITLE
Stworzyć 2 grafiki promujące grę

### ISSUE THREAD

**Issue by exostin** [exostin/ExpiryDate#42]
Wstęp do testów A/B. Stwórzcie 2 wersje grafik promujących grę. Wersję A pokażcie dziesięciu osobom, wersję B kolejnym dziesięciu. Poproście, by każda z tych osób oceniła okładkę gry w skali 1-10. Następnie wyciągnijcie średnią z ocen. Tutaj wklejcie link do obu tych okładek wraz z końcowymi ocenami.

**Comment by exostin** [comment]
![plakat2](https://user-images.githubusercontent.com/18118467/160261299-b6c09c6b-6567-4de7-ac89-42cac588d65a.png)
![plakat1](https://user-images.githubusercontent.com/18118467/160261302-38368d99-cd9e-4d75-b714-beadf8eafe5a.png)

**Comment by Krzyzak321** [comment]
Średnia ocen:
7.5 obrazek 1 
5.1 obrazek 2
